### ISSUE TITLE
Bug with logging

### ISSUE THREAD

**Issue by rogerhi** [abuchanan/kindlespark#1]
Hi 

I got this :

_Python kindlespark.py http://www.sparknotes.com/lit/gatsby/
kindlespark.py:12: ScrapyDeprecationWarning: Module `scrapy.log` has been deprec
ated, Scrapy now relies on the builtin Python library for logging. Read the upda
ted logging entry in the documentation to learn more.
  from scrapy import log, signals
gatsby
Traceback (most recent call last):
  File "kindlespark.py", line 190, in <module>
    main()
  File "kindlespark.py", line 178, in main
    log.start(loglevel=log.DEBUG)
AttributeError: 'module' object has no attribute 'start'_

and I commented out the logging as a first go but that didnt work.

I realise you only put it together in a few hours but as its fairly recent I thought you might have some ideas. 

Thanks in advance.
Roger

**Comment by buchanae** [comment]
Thanks Roger. I'm happy someone is trying to use it! And sad that it didn't
work.

I'll be happy to fix this, but I'm on the road in India for a few months
without a computer.

I'm suprised commenting out the logging code didn't work. Did you get a
different error at that point?

Alternatively you could try installing an old version of scrapy.

**Comment by rogerhi** [comment]
I did get a different error after that point. I have never had a lot of luck with these python scripts. I am too out of touch to do too much with it. I will document the next error i get. Enjoy your trip :)

**Comment by buchanae** [comment]
I've rewritten the code in Go which has eliminated the Scrapy dependency and made the code much simpler to download and use (you can download a binary). If you have the time, please give it a shot and let me know if it work. Thanks!
