### ISSUE TITLE
Unable to rip "Paradise Lost", gives me 1kb opf

### ISSUE THREAD

**Issue by marat569** [abuchanan/kindlespark#2]
I'm trying to get this rip: http://www.sparknotes.com/poetry/paradiselost/

But every time I try, it just gives me a 1kb opf that just says "Table of Contents".

For some reason "gatsby" works, but not paradiselost. Is it because of the /poetry?

Please look into this, thanks!

**Comment by buchanae** [comment]
Thanks for reporting @marat569 

I've changed the CLI arguments to allow a full URL, instead of assuming the base URL is sparknotes.com/lit/

The new command is `./kindlespark paradise-lost http://www.sparknotes.com/poetry/paradiselost/`
